<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniSiniestros.Data\MiniSiniestros.Data.csproj" />
    <ProjectReference Include="..\MiniSiniestros.Services\MiniSiniestros.Services.csproj" />
    <ProjectReference Include="..\MiniSiniestros.ViewModels\MiniSiniestros.ViewModels.csproj" />
  </ItemGroup>

</Project>
